#!/bin/bash

# This script builds a Mup rpm.
# Any arguments will be passed along to the rpmbuild -bb command

MUP_VERSION=6.8
ORIG_SRC_TAR=mup-$MUP_VERSION.tar.gz
if [ ! -f "../$ORIG_SRC_TAR" ]
then
	echo  ../$ORIG_SRC_TAR not found
	exit 1
fi

set -e

mkdir -p rpmtop
for d in BUILD RPMS SOURCES SPECS SRPMS
do
	mkdir -p rpmtop/$d
done

cat mup.spec.in ../ChangeLog > rpmtop/SPECS/mup.spec

MUP_VERSION_NO_DOT=$(echo $MUP_VERSION | tr -d .)
RPM_SRC_TAR=rpmtop/SOURCES/mup${MUP_VERSION_NO_DOT}src.tar.gz
rm -f $RPM_SRC_TAR
ln -s ../../../$ORIG_SRC_TAR $RPM_SRC_TAR
rpmbuild -bb --define "_topdir $(pwd)/rpmtop" $* rpmtop/SPECS/mup.spec
rpmbuild -bs --define "_topdir $(pwd)/rpmtop" rpmtop/SPECS/mup.spec
