#!/bin/sh

# This script makes .gif files for all the examples on the Mup User's Guide.

# Paths to tools are expected to be passed in (GREP, EXPR, CAT, ...)
while [ -n "$1" ]
do
        eval $1
        shift
done

suff=$$

$CAT *.html | $EGREP "mugex[0-9]*.gif|ext_[1234].gif" | $SORT -u | while read name
do
	if echo $name | $GREP -q ext
	then
		name=`$EXPR "$name" : ".*\(ext_[0-9]*.gif\).*"` 
	else
		name=`$EXPR "$name" : ".*\(mugex[0-9]*.gif\).*"` 
	fi
	fname=`$EXPR $name : "\(.*\)\..*"`
	echo converting $fname to GIF.... 
	geom=$(../../tools/doc/addoffset ../../src/mup/prolog.ps ../$fname.ps $fname.$suff)
	# Run Ghostscript and convert the output to gif
	$GS -sDEVICE=ppmraw -sOutputFile=${fname}.ppm -dQUIET $geom -r108 - < ${fname}.$suff
	$PPMTOGIF < ${fname}.ppm > ${fname}.gif
	rm ${fname}.ppm ${fname}.$suff
done

# Do the chart showing all the special music characters
mc_res=150
# We should be able to do just:
#    grep BoundingBox ../muschar.ps | read XX mc_llx mc_lly mc_urx mc_ury
# but that does not work in bash. (It works perfectly well in ksh.)
# So do them the hard way...
mc_llx=$(grep BoundingBox ../muschar.ps | cut -f2 -d' ')
mc_lly=$(grep BoundingBox ../muschar.ps | cut -f3 -d' ')
mc_urx=$(grep BoundingBox ../muschar.ps | cut -f4 -d' ')
mc_ury=$(grep BoundingBox ../muschar.ps | cut -f5 -d' ')
# add a little fuzz around the edge
mc_llx=$($EXPR $mc_llx - 1)
mc_lly=$($EXPR $mc_lly - 1)
mc_urx=$($EXPR $mc_urx + 1)
mc_ury=$($EXPR $mc_ury + 1)
# Calculate width and height
mc_width=$($EXPR $mc_urx - $mc_llx)
mc_width=$($EXPR $mc_width '*' $mc_res / 72)
mc_height=$($EXPR $mc_ury - $mc_lly)
mc_height=$($EXPR $mc_height '*' $mc_res / 72)
echo "-$mc_llx -$mc_lly translate" | $CAT ../../src/mup/prolog.ps - ../muschar.ps | $GS -sOutputFile=muschar.ppm -sDEVICE=ppmraw -r${mc_res} -g${mc_width}x${mc_height} -
$PPMTOGIF < muschar.ppm > muschar.gif
rm muschar.ppm
